/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC998ERC721BottomUp,
  IERC998ERC721BottomUpInterface,
} from "../IERC998ERC721BottomUp";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        internalType: "address",
        name: "_toContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_toTokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "transferToParent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC998ERC721BottomUp__factory {
  static readonly abi = _abi;
  static createInterface(): IERC998ERC721BottomUpInterface {
    return new utils.Interface(_abi) as IERC998ERC721BottomUpInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC998ERC721BottomUp {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC998ERC721BottomUp;
  }
}
