/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Lol, LolInterface } from "../Lol";

const _abi = [
  {
    inputs: [],
    name: "changeFlagA",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Lol__factory {
  static readonly abi = _abi;
  static createInterface(): LolInterface {
    return new utils.Interface(_abi) as LolInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Lol {
    return new Contract(address, _abi, signerOrProvider) as Lol;
  }
}
