/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { TestFacetB, TestFacetBInterface } from "../TestFacetB";

const _abi = [
  {
    inputs: [],
    name: "changeFlagB",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getFlagB",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610228806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80631a93b60c1461003b5780638cb0243914610045575b600080fd5b610043610063565b005b61004d6100c5565b60405161005a91906101d7565b60405180910390f35b3073ffffffffffffffffffffffffffffffffffffffff16632af01b386040518163ffffffff1660e01b8152600401600060405180830381600087803b1580156100ab57600080fd5b505af11580156100bf573d6000803e3d6000fd5b50505050565b60006100e2600060060160149054906101000a900460ff166100fa565b600060060160149054906101000a900460ff16905090565b6101908160405160240161010e91906101d7565b6040516020818303038152906040527f32458eed000000000000000000000000000000000000000000000000000000007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19166020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff8381831617835250505050610193565b50565b60008151905060006a636f6e736f6c652e6c6f679050602083016000808483855afa5050505050565b60008115159050919050565b6101d1816101bc565b82525050565b60006020820190506101ec60008301846101c8565b9291505056fea264697066735822122044245dfa34dcfe9a6109e0c17f80e4f3ebab0445fe34f90af1db87e4231a587964736f6c634300080d0033";

export class TestFacetB__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<TestFacetB> {
    return super.deploy(overrides || {}) as Promise<TestFacetB>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TestFacetB {
    return super.attach(address) as TestFacetB;
  }
  connect(signer: Signer): TestFacetB__factory {
    return super.connect(signer) as TestFacetB__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestFacetBInterface {
    return new utils.Interface(_abi) as TestFacetBInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestFacetB {
    return new Contract(address, _abi, signerOrProvider) as TestFacetB;
  }
}
